### PR TITLE
Add shebang to plugin file to make linting easier

### PR DESCRIPTION
**Pull request by unixorn**
Noticed PR linter was unhappy without a shebang - added.

### CODE REVIEW

**Comment by Bhupesh-V** [comment]
> Noticed PR linter was unhappy without a shebang - added.

Haha.
I was going to ignore the file anyway

**Review by Bhupesh-V — APPROVED** [review]

**Comment by unixorn** [comment]
It's tidier this way, and this also helps editors figure out which syntax highlighter to use

**Comment by Bhupesh-V** [comment]
@unixorn wanted to ask something
if on MacOS, what version of Bash version are you running (since Apple changed their default shell)?

I have done some incompatible changes so ugit won't work in bash v3 and prior

**Comment by unixorn** [comment]
I'm running `zsh` as my login shell - the stock `bash` included on my mac is 3.2.57

```
❯ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by unixorn** [comment]
I install `bash` 5 with homebrew though

```
bash --version
GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin20.3.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by Bhupesh-V** [comment]
> I install `bash` 5 with homebrew though
> 
> ```
> bash --version
> GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin20.3.0)
> Copyright (C) 2020 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> 
> This is free software; you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> ```

I see that's good just wanted to see if it's upgradable or not. We can give up Bash 3 for good now 😅 
For macOS users, 2 things are required

```bash
brew install fzf
brew install bash
```

Thanks for your time and effiort

**Comment by unixorn** [comment]
No problem, glad I was able to help.

**Pull request merged**
